import assert from 'node:assert/strict';
import { installFakeDom } from './fakedom.mjs';
installFakeDom();
Object.defineProperty(globalThis, 'navigator', { configurable: true, value: { platform: 'Linux x86_64' } });
Object.defineProperty(localStorage, 'length', { get: () => Object.keys(localStorage._s).length });
localStorage.key = i => Object.keys(localStorage._s)[i] ?? null;
const { attachToTerminal, ctrlVPasteEnabled } = await import('../public/js/ui/hotkeys.js');
let handler;
const term = { parser: { registerOscHandler() {} }, attachCustomKeyEventHandler(fn) { handler = fn; } };
attachToTerminal(term, () => 'shell');
let checks = 0;
const check = (name, fn) => { fn(); checks++; console.log('PASS '+name); };
const key = extra => { let prevented = false; const accepted = handler({ type:'keydown', code:'KeyV', key:'v', keyCode:86, ctrlKey:true, preventDefault(){prevented=true;}, ...extra }); return {accepted,prevented}; };
check('off by default leaves terminal handling', () => assert.deepEqual(key(), {accepted:true,prevented:false}));
const { openSettings, closeSettings } = await import('../public/js/ui/settings.js');
openSettings();
let toggle = document.querySelectorAll('[data-sec="behavior"] [role=switch]')[1];
check('accessible off switch', () => assert.equal(toggle.getAttribute('aria-checked'),'false'));
toggle._fire('click');
check('setting persists and permits browser native paste', () => { assert.equal(ctrlVPasteEnabled(),true); assert.deepEqual(key(),{accepted:false,prevented:false}); });
closeSettings();openSettings();
check('reopened settings shows saved choice', () => assert.equal(document.querySelectorAll('[data-sec="behavior"] [role=switch]')[1].getAttribute('aria-checked'),'true'));
check('failed persistence restores switch and reports failure',()=>{
  const saved = localStorage.setItem;
  localStorage.setItem = () => { throw new Error('blocked'); };
  document.querySelectorAll('[data-sec="behavior"] [role=switch]')[1]._fire('click');
  localStorage.setItem = saved;
  assert.equal(document.querySelectorAll('[data-sec="behavior"] [role=switch]')[1].getAttribute('aria-checked'),'true');
});
await new Promise(r=>setTimeout(r,20));
check('failed persistence shows honest feedback',()=>assert.ok(document.body.textContent.includes('Could not save this browser setting.')));
for(const extra of [{shiftKey:true},{metaKey:true},{altKey:true},{isComposing:true},{keyCode:229},{type:'keyup'}]) check('unrelated modifiers/composition untouched '+JSON.stringify(extra),()=>assert.equal(key(extra).accepted,true));
const { collectBrowserPrefs, applyBrowserPrefs } = await import('../public/js/ui/backup-restore.js');
check('backup collects behavior preference',()=>assert.equal(collectBrowserPrefs()['clideck.ctrlVPaste'],'true'));
check('unselected restore leaves preference',()=>{applyBrowserPrefs({},['appearance']);assert.equal(ctrlVPasteEnabled(),true);});
check('selected behavior restore applies choice',()=>{applyBrowserPrefs({'clideck.ctrlVPaste':'false'},['behavior']);assert.equal(ctrlVPasteEnabled(),false);});
check('missing selected preference restores default',()=>{localStorage.setItem('clideck.ctrlVPaste','true');applyBrowserPrefs({},['behavior']);assert.equal(ctrlVPasteEnabled(),false);});
Object.defineProperty(globalThis,'navigator',{configurable:true,value:{platform:'MacIntel'}});
const mac = await import('../public/js/ui/hotkeys.js?mac');mac.attachToTerminal(term,()=> 'shell');localStorage.setItem('clideck.ctrlVPaste','true');
check('Mac enabled Ctrl+V handles paste; Cmd+V stays native',()=>{assert.deepEqual(key(),{accepted:false,prevented:true});assert.equal(key({ctrlKey:false,metaKey:true}).accepted,true);});
localStorage.setItem('clideck.ctrlVPaste','false');
check('Mac disabled Ctrl+V retains terminal behavior',()=>assert.deepEqual(key(),{accepted:true,prevented:false}));
closeSettings();console.log(`${checks}/${checks} passed`);
